### ISSUE TITLE
mpi4py is supposedly optional but openrdp fails if it is not installed

### ISSUE THREAD

**Issue by terrycojones** [PoonLab/OpenRDP#102]
https://github.com/PoonLab/OpenRDP says that `mpi4py` is optional. This is not the case at present because `run_scans` in `openrdp/__init__.py` has `from mpi4py import MPI` and does not catch the resulting `ModuleNotFoundError` exception.

**Comment by WilliamZekaiWang** [comment]
Hi, I think I have fixed the issue. I had the import not in the try catch block. Can you try again?

**Comment by terrycojones** [comment]
Hi @WilliamZekaiWang Actually I just sent a pull request https://github.com/PoonLab/OpenRDP/pull/104. It works for me (when I pass `use_mpi=False`). I will uninstall `mpi4py` and try that too.

**Comment by terrycojones** [comment]
The code in my pr (which is basically the same as yours but with an `if self.use_mpi:` wrapped around it) works fine when `mpi4py` is not installed.  Thanks!

**Comment by ArtPoon** [comment]
@WilliamZekaiWang can you please compare your changes with @terrycojones 's PR, reconcile and merge?
