### ISSUE TITLE
MPI fatal error

### ISSUE THREAD

**Issue by terrycojones** [PoonLab/OpenRDP#103]
On OS X 14.5 I installed `mpich` via `brew install mpich` then `pip installed mpi4py`. Then I run `openrdp` and after some time get the following error:

```
Abort(868845583): Fatal error in internal_Finalize: Other MPI error, error stack:
internal_Finalize(48002).........: MPI_Finalize failed
MPII_Finalize(421)...............:
MPID_Finalize(775)...............:
MPIDI_OFI_mpi_finalize_hook(1081):
flush_send_queue(1030)...........:
(unknown)(): Other MPI error
```

It would be nice if there was a way to indicate that MPI should not be used, or to catch the import error in https://github.com/PoonLab/OpenRDP/issues/102

**Comment by ArtPoon** [comment]
Presumably this is covered by your PR?

**Comment by ArtPoon** [comment]
I'll have to go back to my mac to check but I don't think that I installed `mpich` last time - as I recall `openmpi` was the alternative that is more consistent with our Linux development environment... need to confirm when I get back.

**Comment by ArtPoon** [comment]
Close with recent commit to `master` branch
