### ISSUE TITLE
Tools selection 

### ISSUE THREAD

**Issue by PaulaPrietoOliveira** [PoonLab/OpenRDP#108]
Hello!

I am trying to select the tools that I want to use in openrdp, but it is not working: 
time cat recombined_sim1_1.fasta | docker run -i --rm openrdp -m geneconv maxchi chimaera rdp > recombined_sim1_1.fasta.out 2> recombined_sim1_1.fasta.err &

I tried to update, but it is nor working either: 
(base) polivei1:~$  RUN echo 'cat - > /app/in.fa && openrdp /app/in.fa -m bootscan geneconv chimaera maxchi rdp --outfile=/app/out.csv --cfg=/app/cfg.ini 1>&2 && cat /app/out.csv' > /app/driver.sh
zsh: no such file or directory: /app/driver.sh

**Comment by GopiGugan** [comment]
Hi @PaulaPrietoOliveira, you need to add the “-m” option within the Dockerfile. Please see #90
