### ISSUE TITLE
Make Triplet a generator?

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/OpenRDP#49]
Triplet is an object class that is being initialized with the full lists of sequences and labels, and then three integers to index into these lists.  Then we are looping over all possible triplets and constructing a Triplet object at each iteration.  This seems really inefficient to me.  I would rather call Triplet once and call its `next` method to retrieve the next object.

**Comment by ArtPoon** [comment]
I need to fix the unit tests first, then I'll try implementing this change.

**Comment by GopiGugan** [comment]
https://github.com/PoonLab/OpenRDP/blob/676045af328253e450df4d332e46e8dab3519586/openrdp/__init__.py#L251-L258

**Comment by ArtPoon** [comment]
new branch `iss49`, commit 7b7dd25bf38a1d3e992e168e7674869022a823af
