### ISSUE TITLE
should trim the sequence before I run OpenRDP?

### ISSUE THREAD

**Issue by NailouZhang** [PoonLab/OpenRDP#60]
Hi,
When I use OpenRDP with the aligned sequenc fromm mafft, I can't run OpenRDP well. But It can run with the sequence after trimmed by trimal.
my question is whether I should trim the sequence before I run OpenRDP?

**Comment by ArtPoon** [comment]
Sorry for the delayed response @NailouZhang 
can you please describe the dimensions of your input alignment (number of sequences, alignment length) - and if possible, would you be able to send a copy of the data to my university e-mail?
