### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by 123456zrh** [PoonLab/OpenRDP#61]
when install，there is an error:RuntimeError: Python version >= 3.8 required

**Comment by 123456zrh** [comment]
i have upgraded python version to 3.8.10

**Comment by ArtPoon** [comment]
Hi @123456zrh - did this resolve the problem?  If not, then can you please provide some details on your operating system, and the commit number of OpenRDP you are running?

**Comment by 123456zrh** [comment]
already solved,very very thanks&nbsp;
i am trying run,but there is an error:&nbsp;version `GLIBC_2.29' not found , i am trying to solve it




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Art ***@***.***&gt;; 
发送时间: 2023年5月31日(星期三) 下午3:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PoonLab/OpenRDP] install error (Issue #61)





 
Hi @123456zrh - did this resolve the problem?  If not, then can you please provide some details on your operating system, and the commit number of OpenRDP you are running?

**Comment by ArtPoon** [comment]
@123456zrh are you still encountering problems with installing?

**Comment by 123456zrh** [comment]
I have solved it，very thanks



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Art ***@***.***&gt;; 
发送时间: 2023年6月13日(星期二) 晚上9:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PoonLab/OpenRDP] install error (Issue #61)





 
@123456zrh are you still encountering problems with installing?

**Comment by ArtPoon** [comment]
Thanks for the update @123456zrh - For the benefit of other users, it would be great if you could briefly describe how you resolved your problem.  Closing this issue as resolved.

**Comment by abreucd** [comment]
> already solved,very very thanks&nbsp; i am trying run,but there is an error:&nbsp;version `GLIBC_2.29' not found , i am trying to solve it
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Art ***@***.***&gt;; 发送时间: 2023年5月31日(星期三) 下午3:16 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [PoonLab/OpenRDP] install error (Issue #61) Hi @123456zrh - did this resolve the problem? If not, then can you please provide some details on your operating system, and the commit number of OpenRDP you are running? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Hi there, could you please tell me how to resolve the GLIB_2.29 issue?
