### ISSUE TITLE
OpenRDP run slow, Can I speed it up?

### ISSUE THREAD

**Issue by NailouZhang** [PoonLab/OpenRDP#62]
Hi,

When I ran OpenRDP with my sequence (72 taxa and 10,999 sites), it ran for a long time. Can I speed it up?

**Comment by ArtPoon** [comment]
Currently your best option for speed is to run the original RDP.  We are working on improving and optimizing OpenRDP, but this effort is not supported by any research grants, so progress will be slow without help from the community.

**Comment by ArtPoon** [comment]
Thanks!  Bioinformatics is all about the CLI.  Maybe sometime in the near future you might be able to pitch in :-)

**Comment by NailouZhang** [comment]
Hi, 
Are there ways to speed up recombination analysis, such as by setting nucleotide identity thresholds to reduce the number of sequences, or by cutting for highly variable regions?

Before recombination analysis, I tried to remove replicated sequences with cd-hit, then filter columns with trimAl. However, I don't think that these are the right things. Can you give some tips on how to prepare for a recombination analysis?
