### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by paolij** [PoonLab/OpenRDP#70]
Hello, I am tryin to install OpenRDP on my Mac and have an error message pasted below. Do you have any advice on how to navigate past this error message ? Thank you!

Searching for h5py>=3.8.0
Reading https://pypi.org/simple/h5py/
**Download error on https://pypi.org/simple/h5py/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local** issuer certificate (_ssl.c:1000) -- Some packages may not be found!
Couldn't find index page for 'h5py' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000) -- Some packages may not be found!
No local packages or working download links found for h5py>=3.8.0
error: Could not find suitable distribution for Requirement.parse('h5py>=3.8.0')

**Comment by ArtPoon** [comment]
Can you please provide the following information:
* operating system and version
* Python version
* command that led to the error

**Comment by paolij** [comment]
Hi Art,
Thanks for your quick response, much appreciated!

1. MacOS Ventura 13.6.1 
2. python 3.l2
3.sudo python3 setup.py install

**Comment by ArtPoon** [comment]
Hm.  I just ran `python setup.py install` with an updated copy of OpenRDP (master branch) on my Mac, which happens to be running Ventura 13.5.2, and did not run into any issues:
```console
Adding OpenRDP 0.1.0 to easy-install.pth file
Installing openrdp script to /Users/art/venv/bin

Installed /Users/art/venv/lib/python3.11/site-packages/OpenRDP-0.1.0-py3.11.egg
Processing dependencies for OpenRDP==0.1.0
Searching for h5py==3.10.0
Best match: h5py 3.10.0
Adding h5py 3.10.0 to easy-install.pth file
detected new path './OpenRDP-0.1.0-py3.11.egg'

Using /Users/art/venv/lib/python3.11/site-packages
Searching for numpy==1.26.0
Best match: numpy 1.26.0
Adding numpy 1.26.0 to easy-install.pth file
Installing f2py script to /Users/art/venv/bin

Using /Users/art/venv/lib/python3.11/site-packages
Searching for scipy==1.11.3
Best match: scipy 1.11.3
Adding scipy 1.11.3 to easy-install.pth file

Using /Users/art/venv/lib/python3.11/site-packages
Finished processing dependencies for OpenRDP==0.1.0
(venv) art@Wernstrom OpenRDP % 
```
What version of OpenRDP are you trying to install?  Can you try the latest commit on the master branch?  What version of `pip` are you running?

**Comment by paolij** [comment]
Hi Art,

Thank you for this help! I follwed the readme instructions to clone the OpenRDP file using "git clone https://github.com/PoonLab/OpenRDP" so I believe that's the latest commit on the master branch?

**Comment by ArtPoon** [comment]
Given that you mentioned successfully installing the module in #71, I assume this is okay to close.  @paolij can you please make a note of your fix if possible?
