### ISSUE TITLE
Can't use -m parameter

### ISSUE THREAD

**Issue by Wesady** [PoonLab/OpenRDP#75]
HI
When I use command like `openrdp -c test_cfg.ini -m geneconv -o ***.csv ***.fasta`, there's an error: `openrdp: error: argument -m/--methods: invalid choice: '[geneconv]' (choose from 'geneconv', 'bootscan', 'maxchi', 'siscan', 'chimaera', 'threeseq', 'rdp')`. I can't find any help from document. Can you help me?
THANK YOU!

**Comment by WilliamZekaiWang** [comment]
Hi,

I tried to replicate your issue with the the same `test_cfg.ini` file and other arguments you provided in that order and it worked on my end through the latest version of the master branch with the python/dependency versions specified in the readme.

I did see a similar error when I put the command without specifying output and config file:
```
/OpenRDP# openrdp -m genecov test.fasta
usage: openrdp [-h] [-r REF] [-o OUTFILE] [-c CFG] [-m  [...]] [-q] infile
openrdp: error: argument -m/--methods: invalid choice: 'genecov' (choose from 'geneconv', 'bootscan', 'maxchi', 'siscan', 'chimaera', 'threeseq', 'rdp')
```
For some reason, putting `-q` after `-m genecov` and specifying the config file fixed this issue for me. Perhaps it could be a temporary fix for you as well? 
i.e.: `openrdp -c test_config.ini -m genecov -q test.fasta`

Could you also provide more information regarding the python version you are using?

**Comment by Wesady** [comment]
Add `-q` worked, THANK YOU VERY MUCH!

**Comment by ArtPoon** [comment]
Something's weird about this - that should not have worked because there's a typo in `genecov`

**Comment by Wesady** [comment]
Yeah, but what I used is `geneconv`. And my operating system is Ubuntu 20.04.6 LTS, version of Python is 3.9.18, version of OpenRDP was cloned from this repository on Feb 2nd.

**Comment by ArtPoon** [comment]
Closing with a no repro
