### ISSUE TITLE
Multiple comparison correction and permutation

### ISSUE THREAD

**Issue by Oliveira-Hugo** [PoonLab/OpenRDP#82]
Hello Art, 

I would like to ask you if OpenRDP implements two functionalities from RDP:
	1-The multiple comparison correction for modifying p-value cutoff as dataset size;
	2-Integration with permutation tests for applying simulations on the dataset.
	
They're both listed on the [RDP5 Manual](http://web.cbio.uct.ac.za/~darren/RDP5Manual.pdf) on sections 3.1.1 and 3.1.2.

Thank you in advance and congrats for the initiative, I think OpenRDP is a great project.

**Comment by ArtPoon** [comment]
Thanks @Oliveira-Hugo.  Implementation of OpenRDP was based on RDP version 4.  I don't recall those two features being implemented.  We can add them as feature requests to the issue tracker, but I can't promise that they would get resolved in the short term!

**Comment by Oliveira-Hugo** [comment]
> Thanks @Oliveira-Hugo. Implementation of OpenRDP was based on RDP version 4. I don't recall those two features being implemented. We can add them as feature requests to the issue tracker, but I can't promise that they would get resolv

**Comment by Oliveira-Hugo** [comment]
@ArtPoon Thank you for your response and consideration!
