### ISSUE TITLE
进程池使用错误 (Process pool usage error)

### ISSUE THREAD

**Issue by pathogen-detection** [PoonLab/OpenRDP#87]
with multiprocessing.Pool(self.np) as p:
            tempfiles = p.map(self.scan, range(0, align.shape[1], self.step_size))，
在Windows系统中上述脚本只能放在if __name__ == '__main__':之下。

**Comment by ArtPoon** [comment]
> 在Windows系统中上述脚本只能放在if name == 'main':之下
*In Windows systems, the above script can only be placed under if name == 'main':*

Thanks for reporting this issue.  We'll look into it.

**Comment by ArtPoon** [comment]
I think we will be deprecating `multiprocessing` in favour of `mpi4py` for bootscan, see #85

**Comment by ArtPoon** [comment]
Close issue upon moving MPI functionality into main branch
