### ISSUE TITLE
The option -m does not recognize the method

### ISSUE THREAD

**Issue by PaulaPrietoOliveira** [PoonLab/OpenRDP#90]
Hello!
I am trying to run the openrdp with only one method with the option -m, but it is running all the methods. How can I solve this, please? 

 time cat test_neisseria.fasta | docker run  -i --rm openrdp -m bootscan > neisseria_result.csv && docker stats --no-stream

**Comment by GopiGugan** [comment]
Hi @PaulaPrietoOliveira, you need to update the `Dockerfile` and add the `-m` option:

https://github.com/PoonLab/OpenRDP/blob/bb0200092d6245cfd11784a1e7fd081a59507de1/Dockerfile#L51-L54

For example, if you want to run `bootscan`, you would update the instruction as follow:

`RUN echo 'cat - > /app/in.fa && openrdp /app/in.fa -m bootscan --outfile=/app/out.csv --cfg=/app/cfg.ini 1>&2 && cat /app/out.csv' > /app/driver.sh`
